name: build
on: push

jobs:
  build:
    strategy:
      matrix:
        java: [ 17-jdk ]
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # Build


      - name: Build
        run: ./gradlew build

      # Upload

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: ./build/libs/
